spring.cloud.config.discovery.enabled=false
#spring.cloud.config.discovery.service-id=CONFIG-SERVICE
#spring.config.import=optional:configserver:

spring.cloud.config.fail-fast=false
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.multiplier=1.3
spring.cloud.config.retry.max-interval=20000
spring.cloud.config.retry.max-attempts=20

#spring.redis.host=localhost
#spring.redis.port=6379

spring.output.ansi.enabled=ALWAYS

spring.cloud.gateway.filter.request-rate-limiter.deny-empty-key=false
spring.main.allow-bean-definition-overriding=true
